### ISSUE TITLE
Raiding or stealing for guilds

### ISSUE THREAD

**Issue by schnapster** [anok/robin-rpg#12]
The chat came up with the idea of having some interaction between the guilds. After all, currently the only real incentive to have different guilds is some rivalry roleplaying, so we should support that.

The idea basically is, every X minutes a guild can raid one of the other guilds and steal X loot from their stash. This could be done like so:

guildAmember1: !raid guildB
rpg-bot: guildA started a raid on guildB. guildA has 5 minutes to participate by posting !raid guildB, guildB may defend by posting !defend
guildAmember2: !raid guildB
guildAmember3: !raid guildB
guildBmember1: !defend
guildBmember2: !defend
rpgbot: guildAs raid of 3 successfully raided guildBs 2 defenders and stole a shiny!
OR
rpgbot: guildBs 2 defenders parried the vicious attack of 3 players of guildA!

To encourage roleplaying messages over 60 chars get a bonus on the raid/defend values. Only one message per player should be counted though.

As the objective is to have some rivalling guilds, it should be balanced around smaller guilds having it easier to steal a shiny from bigger guilds than the other way round, so this should keep the guilds equally strong while allowing an active guild still go ahead, and the smaller to catch up faster.

**Comment by Nicholaiii** [comment]
+1

**Comment by jpratt9** [comment]
+1

**Comment by anok** [comment]
+1
