### ISSUE TITLE
warn players about !deposit's default "deposit all" before actually depositing

### ISSUE THREAD

**Issue by jpratt9** [anok/robin-rpg#13]
This is a serious problem for all players who might just want a tooltip-like explanation of the command. 

If anything, !deposit should default to depositing 1 item to me. 

Or maybe we need a separate command for doing everything at once, eg "!depositall". This keeps the players happier (especially those of us who do not know what it does, and accidentally deposit all 90 of their items).

**Comment by LorenzGardner** [comment]
it defaulted to all back before you could deposit less than all. But yeah, 1 is a good default.

(but go ahead and dump those 90 items, now that loot is random the xp boost from the guild is more important)
