### ISSUE TITLE
making inventory visible via !loot

### ISSUE THREAD

**Issue by jpratt9** [anok/robin-rpg#6]
It wouldn't be too impractical to implement this. Just make every user a JSON object with name and array of loot. Then parse this upon !loot, or some other command. So for example:
`#rpg !loot`
`#rpg Your loot is: Item 1, Item 2, Item 3...` 
or 
`#rpg Your loot is: Item 1, Item 2, ..., Item LAST`

**Comment by anok** [comment]
With the 140 chars limit it would be pretty useless, i think.

**Comment by jpratt9** [comment]
Write loot to a google doc then? Or is that too memory intensive?

**Comment by jpratt9** [comment]
Some kind of persistance of data is what I'm thinking is the backbone to this

**Comment by anok** [comment]
Solved ;3
