### ISSUE TITLE
Distribute the loot randomly

### ISSUE THREAD

**Issue by schnapster** [anok/robin-rpg#8]
Right now a lot of new people trying it out get frustrated cause they almost never seem to get lootdrops. The code gives it to the slayer/lasthit of the monster, which in most cases will be someone who already outputs a lot of damage. Let's make the game it more accessible by randomizing the receiver of the loot through all players of the party.

**Comment by anok** [comment]
Yeah, will do it once i get get off work :+1:

**Comment by anok** [comment]
Or you can do it and I will merge into master latter :3

**Comment by schnapster** [comment]
I wanted to hear your thoughts first! I'll implement it. There is already a branch with some nice changes, I'll put it there.

**Comment by anok** [comment]
I did another branch. But i cannot test it now.

**Comment by anok** [comment]
The last hit still gets extra XP, btw.

**Comment by schnapster** [comment]
I like it that way. It keeps trying to deal the killing blow as kind of a minigame.
I pulld the random loot destribution into my branch and tested it, there was a minor bug, but it seems to work now as it should. You can close this issue when you merge the cleanup branch into master.
